# Copyright (c) 2022, ZiChenStudio Official
title: ZiChen Blog
baseurl: "" # For github pages
description: >- # You can edit footer in _includes/footer.md 
  This is an ultralight demo.

google_analytics: # Enter your tracking ID. Not available on IPFS

twitter_cards: off # Not available on IPFS. /assets/logo.png required
twitter_username: 

# Build settings
markdown: kramdown
sass:
  style: compressed

future: BOOL
